# Generated by Django 3.2.7 on 2021-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('L', 'Livro'), ('F', 'Filme'), ('J', 'Jogo'), ('A', 'Anime')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
