# Generated by Django 3.0.8 on 2021-10-07 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('L', 'Livro'), ('F', 'Filme'), ('J', 'Jogo'), ('A', 'Anime')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioClube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.Clube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('texto', models.CharField(max_length=10000)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.Clube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.Usuario')),
            ],
        ),
    ]
