# Generated by Django 3.2.7 on 2021-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_storie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storie',
            name='clube_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storie',
            name='usuario_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
