# Generated by Django 3.2.7 on 2021-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_auto_20211004_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storie',
            name='texto',
            field=models.CharField(max_length=9223372036854775807),
        ),
    ]
