# Generated by Django 3.2.7 on 2021-10-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0004_alter_storie_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storie',
            name='clube_id',
        ),
        migrations.RemoveField(
            model_name='storie',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='storie',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.clube'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storie',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.usuario'),
            preserve_default=False,
        ),
    ]
