# Generated by Django 3.2.7 on 2021-10-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0005_auto_20211004_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UsuarioClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.clube')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clube.usuario')),
            ],
        ),
    ]
